files:
  - source: /**/**.md
    ignore:
      - /.github/
      - /.vitepress/
      - pnpm-lock.yaml
      - package.json
      - .gitignore
      - LICENSE
      - /**/%locale_with_underscore%/
      - preference.md
    translation: /%original_path%/%locale_with_underscore%/%original_file_name%
