blank_issues_enabled: true
contact_links:
  - name: 问题 & 讨论 & 建议
    url: https://github.com/travellings-link/travellings/discussions
    about: 使用 GitHub 讨论进行留言板式的问题和讨论或功能建议
  - name: 生活类博客收录申请 & 信息修改申请
    url: https://jinshuju.net/f/RqMPiX
    about: 方便生活类博客申请收录，可以更快地得到处理
