# Issue reopen 时自动标记“待处理”标签
# 用于当站点失效时重新打开 Issue 通知站长

name: 【Reopen】Label and move to project on issue reopen
on:
  issues:
    types: [reopened]

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issue
        uses: andymckay/labeler@master
        with:
          add-labels: "待回应"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
